# Generated by Django 4.1.7 on 2023-05-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quorapp', '0002_question_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
